sudo: required
dist: trusty
language: cpp

matrix:
  include:
    -
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - build-essential
            - software-properties-common
            - g++-6
            - cmake
      env: CXX=g++-6

before_install:
  - set -e # Fail the whole script whenever any command fails

install:
  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
      export CXX=g++-6
    else
      brew install cmake
    fi

script:
  - mkdir build && cd build
  - cmake ..
  - make
